# Generated by Django 2.2.6 on 2019-11-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('dis', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
