# Generated by Django 2.2.6 on 2019-11-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
